# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WeaviateCloud < Formula
  desc "Weaviate Cloud CLI — agent-first provisioning over the Weaviate Cloud API"
  homepage "https://weaviate.io"
  version "0.1.0-rc3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weaviate/weaviate-cloud/releases/download/v0.1.0-rc3/weaviate-cloud_0.1.0-rc3_darwin_amd64.tar.gz"
      sha256 "227be21236500977d38a2d4dd5a8ea39af05bc64fea7240c0e34dca87b4bb121"

      define_method(:install) do
        bin.install "wcloud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weaviate/weaviate-cloud/releases/download/v0.1.0-rc3/weaviate-cloud_0.1.0-rc3_darwin_arm64.tar.gz"
      sha256 "34126ddc5ff4bbe299d98149fb6d25105009a5cf96a46d9487c3e562a7eed547"

      define_method(:install) do
        bin.install "wcloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/weaviate/weaviate-cloud/releases/download/v0.1.0-rc3/weaviate-cloud_0.1.0-rc3_linux_amd64.tar.gz"
      sha256 "e8c8fb5105aa49f739be5cd7ac433150651a73a02b693dda61190226cfff974e"
      define_method(:install) do
        bin.install "wcloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weaviate/weaviate-cloud/releases/download/v0.1.0-rc3/weaviate-cloud_0.1.0-rc3_linux_arm64.tar.gz"
      sha256 "11c849981c0fd9efc2a57b04c385753a9d459b4af9544a701cbc5c0b1b400b2d"
      define_method(:install) do
        bin.install "wcloud"
      end
    end
  end
end
